Document: cups-ksmb
Title: Debian cups-ksmb Manual
Author: <insert document author here>
Abstract: This manual describes what cups-ksmb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cups-ksmb/cups-ksmb.sgml.gz

Format: postscript
Files: /usr/share/doc/cups-ksmb/cups-ksmb.ps.gz

Format: text
Files: /usr/share/doc/cups-ksmb/cups-ksmb.text.gz

Format: HTML
Index: /usr/share/doc/cups-ksmb/html/index.html
Files: /usr/share/doc/cups-ksmb/html/*.html
